- name: Luxury and Comfort
  description: Flying should be a pleasure and we'll make your charter experience as luxurious and comfortable as possible.
  icon: luxury_ico

- name: Worldwide
  description: We do not know from which word the word Charter came, but in our case it is clearly from the expression "It's just cool!". Although, we do not try to surprise. Our task is your wonderful emotions from the service.
  icon: globe_ico

- name: Modern aircraft
  description: On modern aircraft, we are able to provide the highest possible comfort and efficiency in solving problems from a flight. Much more difficult with airships. But we will get through this...
  icon: airplane_ico

- name: Safety and Security
  description: On modern aircraft, we are able to provide the highest possible comfort and efficiency in solving problems from a flight. Much more difficult with airships. But we will get through this...
  icon: safety_ico

- name: Experienced Crew
  description: The experience of the invited crews would be the envy of the aces of the modern air force, but in the case of piloting with you on board, they will not allow themselves aerobatics. But a soft take-off, a pleasant flight and a soft landing will definitely provide.
  icon: crew_ico

- name: Additional Services
  description: For a long time we puzzled over what other additional services we could offer - the whole range of conceivable ones is at your service. Surprise us - wish something unknown to us!
  icon: stewardess_ico